export const CATEGORY_LABELS: Record<string, string> = {
  artigo_periodico: "Artigo em Periódico Indexado",
  livro: "Livro",
  capitulo_livro: "Capítulo de Livro",
  trabalho_anais_resumo: "Trabalho em Anais (Resumo)",
  trabalho_anais_completo: "Trabalho em Anais (Completo)",
  textos_jornal_revista: "Textos em Jornal ou Revistas",
  participacao_evento: "Participação em Eventos Culturais/Científicos",
  palestrante_conferencista: "Palestrante, Conferencista ou Ministrante",
  apresentacao_oral_poster: "Apresentação Oral ou Pôster",
  premios_academicos: "Prêmios Acadêmicos/Científicos",
  software_computacional: "Software Computacional",
  software_multimidia: "Software Multimídia",
  produto_tecnologico_projeto: "Produto Tecnológico (Projeto)",
  produto_tecnologico_prototipo: "Produto Tecnológico (Protótipo)",
  produto_tecnologico_estudo_piloto: "Produto Tecnológico (Estudo Piloto)",
  relatorios_pesquisa: "Relatórios, Processos e Pareceres",
  restauracao_obras: "Restauração de Obras",
  elaboracao_mapa: "Elaboração de Mapa, Carta ou Similar",
  colegiados_congregacao: "Colegiados e Congregação",
  conselhos_superiores_ufr: "Conselhos Superiores da UFR",
  comissoes_permanentes_ufr: "Comissões Permanentes da UFR",
  membro_comissoes_grupos: "Membro de Comissões/Grupos de Trabalho",
  cargo_diretivo_da_ca_liga: "Cargo Diretivo (DA, CA, Ligas Acadêmicas)",
  empresa_junior_diretivo: "Empresa Júnior – Diretivo",
  empresa_junior_assessor: "Empresa Júnior – Assessor",
  empresa_junior_participante: "Empresa Júnior – Participante",
  mesario_eleitoral: "Mesário em Processo Eleitoral",
  curso_extensao: "Curso de Extensão ou Aperfeiçoamento (horas)",
  disciplina_outro_curso: "Aprovação em Disciplina de Outro Curso",
  acao_social_extensionista: "Ação Social, Comunitária ou Extensionista (horas)",
  estagio_nao_obrigatorio: "Estágio Supervisionado Não Obrigatório",
};
